### ISSUE TITLE
Support for SpringBoot 3 + Reactor Kafka

### ISSUE THREAD

**Issue by patpatpat123** [LeoFuso/actuator-kafka#3]
Hello Leo,

First of all, I wanted to say thanks for this very cool project.
It is very useful, easy to read.

I was wondering, could you help bump this project up to SpringBoot 3, as it has been released.

Most of all, your design is based on Spring Kafka. 
Could you help with Reactor Kafka?
Reactive applications are on the rise, and having an actuator reactor kafka would definitely be a plus.

Thank you

**Comment by LeoFuso** [comment]
Hi, Pat! I'm really glad that you found this project useful. 

I can bump to SpringBoot 3, I see no problem with it, it should be a simple task. I'm not sure if it is worth it, tho. 

Just after I finished with the development of this Actuator functionality I discovered that the Spring Kafka client has the capability of auto-reconnect after a Broker failure or eventual timeout situation. In other words, there's not much use in having an Actuator probing for a health check if no actions were needed. In the production environment, my team and I kind of abandoned the use of this endpoint.

That said, if you still feel like this feature is somewhat useful, I can take a look at that, for sure! Let me know.


... about the Reactor implementation, if you have any idea of how this could be done, feel free to share it!

**Comment by patpatpat123** [comment]
Thank you, Leo for your answer.

I believe having such endpoint would be very beneficial.

I understand Kafka consumers has built in reliability features, and also agree those are very useful already. 

But having an actuator endpoint for health, which drills down all the way to Kafka, where we can have monitoring systems polls the endpoint and parse the Kafka health can be a great addition.

Would be great if you can take a small look!

Thank you in advanced.

**Comment by LeoFuso** [comment]
Done!
